### PR TITLE
Fast forward master to upstream master.

### PR DESCRIPTION
**Pull request by rbevers**

### CODE REVIEW

**Review by caffodian — CHANGES_REQUESTED** [review]
Sorry for not thinking of this sooner -

it looks like the .travis.yml file removes Django 1.8 at some point, in this commit: https://github.com/stephenmcd/mezzanine/commit/a06566fcb817637604bc61938885f76175ab01c8#diff-354f30a63fb0907d4ad57269548329e3

https://github.com/stephenmcd/mezzanine/commits/master/.travis.yml


Maybe we should go to the last commit before this with passing tests on the mezzanine side?  

I mean, it might just work, but...

**Comment by caffodian** [comment]
This is pretty stupid.  See the lack of green checks on https://github.com/stephenmcd/mezzanine/commits/master?after=1196c759295f181893718a6bf8f432dee63f834f+34

**Comment by caffodian** [comment]
Hey, so _maybe_ we can use 4.3 after all.... except for this issue https://github.com/stephenmcd/mezzanine/issues/1903

**Comment by caffodian** [comment]
This is a bizarre thread that turns from Django 1.11 to 2.0 partway through and might be responsible for my original confusion 
https://github.com/stephenmcd/mezzanine/issues/1749

**Comment by rbevers** [comment]
Per above ☝️

**Pull request closed without merging**
