### PR TITLE
Pull upstream origin

### PR DESCRIPTION
**Pull request by jacobhamblin**
Played a bit with this locally, didn't notice any issues. It might take a little longer to load a user and its permissions than the official branch? Not sure, seems fine.

Changing the django version from 1.11 to 2.0 leads to some errors in the console, though. Hoping that's not indicative of incompatibility and there are extra steps for django.

### CODE REVIEW

**Comment by caffodian** [comment]
What are the console errors?

**Review by caffodian — APPROVED** [review]

**Comment by caffodian** [comment]
We are no longer using this fork (in prod) anyway, so this should be ok to play with

**Review by rbevers — APPROVED** [review]
What he said ☝️ :shipit:

**Comment by jacobhamblin** [comment]
> What are the console errors?

Think it was list index out of range with a stack trace entirely in Django files

**Pull request merged**
